apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keycloak-monitor
  namespace: observability 
  labels:
    release: kube-prom-stack 
spec:
  selector:
    matchLabels:
      app: keycloak 
  namespaceSelector:
    matchNames:
      - default 
  endpoints:
    - port: http 
      path: /metrics 
      interval: 30s 
