apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-monitor
  namespace: observability
  labels:
    release: kube-prom-stack 
spec:
  selector:
    matchLabels:
      app: rabbitmq 
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
