apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector: { matchLabels: { app: minio } }
  template:
    metadata: { labels: { app: minio } }
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: data
              mountPath: /data

      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-04-22T22-12-26Z
          args: ["server", "/data", "--console-address", ":9001"]
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_SERVER_URL
            - name: MINIO_BROWSER_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_BROWSER_REDIRECT_URL   
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_PROMETHEUS_AUTH_TYPE
            - name: MINIO_NOTIFY_AMQP_ENABLE_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_ENABLE_rabbitmq
            - name: MINIO_NOTIFY_AMQP_URL_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: AMQP_URL_ENV
            - name: MINIO_NOTIFY_AMQP_EXCHANGE_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_EXCHANGE_rabbitmq
            - name: MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_rabbitmq
            - name: MINIO_NOTIFY_AMQP_ROUTING_KEY_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_ROUTING_KEY_rabbitmq
            - name: MINIO_NOTIFY_AMQP_MANDATORY_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_MANDATORY_rabbitmq
            - name: MINIO_NOTIFY_AMQP_DURABLE_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_DURABLE_rabbitmq
            - name: MINIO_NOTIFY_AMQP_FORMAT_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_FORMAT_rabbitmq
            - name: MINIO_NOTIFY_AMQP_COMMENT_rabbitmq
              valueFrom:
                secretKeyRef:
                  name: securedrop-secrets
                  key: MINIO_NOTIFY_AMQP_COMMENT_rabbitmq

          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data


      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
