apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securedrop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/adreaskar/securedrop.git
    targetRevision: manifests
    path: .
    directory:
      recurse: true
      exclude: "{observability-values.yaml,helm-values/**,kustomization.yml}"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true