apiVersion: batch/v1
kind: Job
metadata:
  name: thingsboard-init-job
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: "thingsboard-role"
        vault.hashicorp.com/agent-inject-secret-config.env: "secret/data/securedrop/thingsboard"
        vault.hashicorp.com/agent-inject-template-config.env: |
          {{- with secret "secret/data/securedrop/thingsboard" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end -}}
    spec:
      serviceAccountName: thingsboard-sa
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-thingsboard
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for ThingsBoard..."
              until nc -z thingsboard 9090; do
                echo "Sleeping 5s..."
                sleep 5
              done

      containers:
        - name: init-script
          image: python:3.12-slim
          command:
            - sh
            - -c
            - |
              set -e

              if [ ! -f /vault/secrets/config.env ]; then
                echo "ERROR: Vault config not found"
                exit 1
              fi

              . /vault/secrets/config.env

              if [ -z "$TB_ADMIN_USER" ]; then
                echo "ERROR: TB_ADMIN_USER is missing"
                exit 1
              fi

              if [ -z "$TB_ADMIN_PASS" ]; then
                echo "ERROR: TB_ADMIN_PASS is missing"
                exit 1
              fi

              echo "Installing Python dependencies..."
              pip install --no-cache-dir requests

              echo "Running ThingsBoard init script..."
              python /config/init_thingsboard.py

              echo "ThingsBoard init job completed."
          env:
            - name: TB_URL
              value: "http://thingsboard:9090"
          volumeMounts:
            - name: config-volume
              mountPath: /config

      volumes:
        - name: config-volume
          configMap:
            name: thingsboard-init-config