apiVersion: apps/v1
kind: Deployment
metadata:
  name: securedrop-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securedrop-webapp
  template:
    metadata:
      labels:
        app: securedrop-webapp
    spec:
      containers:
        - name: securedrop-webapp
          image: securedropgr/securedrop:0.1.0
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
