apiVersion: v1
kind: Service
metadata:
  name: securedrop-webapp-service
  labels:
    app: securedrop-webapp
spec:
  type: ClusterIP
  selector:
    app: securedrop-webapp
  ports:
    - port: 8081       
      targetPort: 8081  
