- name: Deploy SecureDrop manifests from local machine
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    k8s_root: "/home/liks/securedrop"

    observability_namespace: "observability"
    observability_release: "kube-prom-stack"
    observability_values_file: "{{ k8s_root }}/observability-values.yaml"

    k8s_manifest_folders:
      - middleware
      - keycloak
      - minio
      - rabbitmq
      - clamav
      - nodered
      - thingsboard
      - api
      - scanner
      - webapp
      - servicemonitor
      - ingress

    cluster_issuer_file: "cluster-issuer-traefik.yaml"

  tasks:
    - name: Check kubectl access to cluster
      command: kubectl get nodes
      changed_when: false

    - name: Check Helm access to cluster
      command: helm list -A
      changed_when: false

    - name: Check observability values file exists
      stat:
        path: "{{ observability_values_file }}"
      register: observability_values_stat

    - name: Add Prometheus Community Helm repo
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      register: prometheus_repo_result
      changed_when: >
        'has been added' in prometheus_repo_result.stdout or
        'has been added' in prometheus_repo_result.stderr
      failed_when: >
        prometheus_repo_result.rc != 0 and
        'already exists' not in prometheus_repo_result.stderr

    - name: Update Helm repos
      command: helm repo update
      changed_when: false

    - name: Upgrade observability stack with custom values
      command: >
        helm upgrade {{ observability_release }} prometheus-community/kube-prometheus-stack
        -n {{ observability_namespace }}
        -f {{ observability_values_file }}
      register: observability_upgrade_result
      changed_when: >
        'has been upgraded' in observability_upgrade_result.stdout or
        'Release' in observability_upgrade_result.stdout
      when: observability_values_stat.stat.exists

    - name: Apply Kubernetes folders in order
      command: "kubectl apply -f {{ k8s_root }}/{{ item }}/"
      loop: "{{ k8s_manifest_folders }}"
      register: apply_result
      changed_when: >
        'created' in apply_result.stdout or
        'configured' in apply_result.stdout

    - name: Apply ClusterIssuer
      command: "kubectl apply -f {{ k8s_root }}/{{ cluster_issuer_file }}"
      register: issuer_result
      changed_when: >
        'created' in issuer_result.stdout or
        'configured' in issuer_result.stdout

    - name: Show certificates
      command: kubectl get certificate,order,challenge
      register: cert_result
      changed_when: false
      failed_when: false

    - name: Print certificates
      debug:
        var: cert_result.stdout_lines

    - name: Show pods
      command: kubectl get pods -o wide
      register: pods_result
      changed_when: false

    - name: Print pods
      debug:
        var: pods_result.stdout_lines